apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: node-evan
  name: node-evan
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-evan
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: node-evan
    spec:
      containers:
      - image: 420361828844.dkr.ecr.ap-southeast-1.amazonaws.com/xendit/iss/evan-node:latest
        imagePullPolicy: ""
        name: node-evan
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
